### ISSUE TITLE
Add testing

### ISSUE THREAD

**Issue by jroo** [cfpb/django-nudge#10]
So much for TDD.  Never too late for DDT.

**Comment by virtix** [comment]
Tests?! We don't need no stinkin' tests!

**Comment by rosskarchner** [comment]
@virtix are you in the office tomorrow? I'd like to chat about nudge testing. I'll be at 1801.

**Comment by virtix** [comment]
Yep. Let us dive into all things testy.

**Comment by rosskarchner** [comment]
I think testing is in a pretty good place right now-- closing this.
