### ISSUE TITLE
add key generator

### ISSUE THREAD

**Issue by jroo** [cfpb/django-nudge#12]
both as a management command and in the admin interface

**Comment by jroo** [comment]
generate_key method now exists in utils.py.  we need to add this to the admin interface.

**Comment by rosskarchner** [comment]
Proposed flow:
- By default, local and remote keys are obscured
- User can check a box, indicating that they accept the risk that comes with keys being displayed. Explanation also includes an alternate, safer (command-line driven) process for viewing and updating keys

**Comment by rosskarchner** [comment]
- if box is checked and form submitted, user can:
- edit the remote key
- see (but not edit) the local key.
- click a button to generate a new local key

**Comment by rosskarchner** [comment]
The flow described above has NOT yet been achieved-- but there is now a button in admin that will regenerate the key.

**Comment by rosskarchner** [comment]
The initial request has been satisfied, and I'm opening a new (feature request) issue for the workflow I described above.
