### ISSUE TITLE
Flesh out exceptions

### ISSUE THREAD

**Issue by jroo** [cfpb/django-nudge#16]
Exceptions will exist everywhere.  Let's think through these, where to throw them and how they will be represented by a server response.

**Comment by jroo** [comment]
exception will be needed when attempting to delete a record that no longer exists on production

**Comment by rosskarchner** [comment]
Added some screenshots to the bottom of this commit, showing how exceptions are handled in admin: https://github.com/jroo/django-nudge/commit/a6f0495f6cf34e6aa545542827ebdee542c3be2b

**Comment by jroo** [comment]
Pushing to v2
