### ISSUE TITLE
Push history items are being deleted with batches

### ISSUE THREAD

**Issue by jroo** [cfpb/django-nudge#20]

**Comment by rosskarchner** [comment]
This seems reasonable to me-- without a batch, this history item has no context. 

I could imagine a richer history item, though, only loosely coupled with Batch, and with a direct association with with either the BatchItems or the underlying versions.

**Comment by jroo** [comment]
I guess it's the ability to delete a batch after a push that's odd, not that the history is being killed with it.  Should we instead disable the ability to delete pushed batches?

**Comment by rosskarchner** [comment]
Makes sense to me

**Comment by rosskarchner** [comment]
Fun discovery-- by setting on_delete=models.PROTECT on the foriegnkey relationship, the batch becomes basically undeletable without deleting the history items first

**Comment by rosskarchner** [comment]
and, since history items aren't exposed in admin, batches essentially can't be deleted

**Comment by rosskarchner** [comment]
commited that change, closing
