### ISSUE TITLE
nudgeinit breaks on when reversion and data are out of sync

### ISSUE THREAD

**Issue by jroo** [cfpb/django-nudge#30]
Expected behavior, but could be problematic for users.  

'''
  File/nudge/utils.py", line 14, in latest_objects
    latest_obj=get_for_object(o)[0]
  File "/usr/local/lib/python2.6/dist-packages/reversion/revisions.py", line 503, in get_for_object
    return self.get_for_object_reference(obj.**class**, obj.pk)
AttributeError: 'NoneType' object has no attribute 'pk'
'''

**Comment by rosskarchner** [comment]
How do these get out of sync?

**Comment by jroo** [comment]
![Guilty Dog](http://3.bp.blogspot.com/-Ib7ibF1O1V8/Tqph-8g_OZI/AAAAAAAAGZI/9DEe38kdXqU/s1600/guilty-dog-26106.jpg)
