### ISSUE TITLE
What's the use of batch.start_date

### ISSUE THREAD

**Issue by jaap3** [cfpb/django-nudge#52]
The batch class has a field called "start_date" but I can't figure out what it's used for.

It defaults to date.today since that's what "default_batch_start_date" returns.

The comment of "default_batch_start_date" suggests that it should default to "date last completed batch pushed or date of earliest revision or today".

I can't find any method that uses this date field.

**Comment by rosskarchner** [comment]
That should control how far back to look for Version's-- and yeah, the intended-not-yet-implemented functionality is that it should default to the date you last pushed (That's another RAMP-ism, that I we could be talked out of)
