### ISSUE TITLE
settings assume pk=1

### ISSUE THREAD

**Issue by jroo** [cfpb/django-nudge#9]
find a better way.  don't rely on id, maybe enforce that only one setting record exists? possibly move settings out of database and into a file?

**Comment by rosskarchner** [comment]
I considered suggesting settings move to settings.py-- although I admit being able to edit them in the Wordpress admin is a nice feature of RAMP.

I'd be on board for migrating them to settings.py or a separate file if you agree.

**Comment by jroo** [comment]
Yeah, I like the ability to edit them in admin, too.  Is it safe to assume pk will always be 1?  Will the admin enforce this?  If not should we enforce that just one record exists no matter what the id and just grab it?

**Comment by rosskarchner** [comment]
Right now admin does enforce it

**Comment by jroo** [comment]
Nice. Does admin explicitly enforce that the id will always be 1 or does it just enforce one record (and the id could be anything)?

**Comment by rosskarchner** [comment]
It doesn't acknowledge that other settings objects might exist: if you try to add one or look at the list, it does a get_or_create for pk=1, and redirects you to edit it

**Comment by jroo** [comment]
Thanks fo the clarification.  I'm closing this since settings should assume that pk=1.

**Comment by rosskarchner** [comment]
http://word.bitly.com/post/19183796149/infrastructure-as-a-platform
